
services:
  app:
    build:
      context: .
    container_name: auth_service
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=auth
      - APP_PORT=8080
      - JWT_SECRET=a3b47f914c35f72c68d3f8e649e9b4fcbc9e35e01b34df65c6d1c8d7b30c122f
      - DB_DEBUG=true
      - MIGRATION_VERSION=1
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: auth
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "user", "-puserpassword"]
      interval: 10s
      timeout: 5s
      retries: 5
